export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL';
export const AUTH_SUCCESSFUL = 'AUTH_SUCCESSFUL';
export const LOGOUT = 'LOGOUT';
export const APOD_LOADING = 'APOD_LOADING';
export const APOD_LOADED = 'APOD_LOADED';
export const APOD_ERROR = 'APOD_ERROR';
